on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get go version
        id: get-go-version
        run: |
          echo "go-version=$(head -n 3 go.mod | tail -n 1 | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.get-go-version.outputs.go-version }}

      - name: get go caches
        id: get-go-caches
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.get-go-caches.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: go mod cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.get-go-caches.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - run: go build -v ./...

      - run: go vet -v ./...

      - run: go test -v ./...
